# Generated by Django 3.0.5 on 2020-07-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cd_url", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customurl",
            name="acknowledged",
            field=models.BooleanField(
                db_column="Acknowledged",
                default=True,
                help_text="Used to flag if this link has been acknowledged as up-to-date. If not, managers are notified that the links need to be updated.",
                verbose_name="Acknowledged",
            ),
        ),
        migrations.AddField(
            model_name="customurl",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_column="LastUpdated",
                help_text="Used to send notifications to administrators when the link needs to be updated",
                verbose_name="Last Updated",
            ),
        ),
        migrations.AddField(
            model_name="customurl",
            name="notify_in",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_column="NotifyIn",
                default=12,
                help_text="The number of hours, days or months until managers are notified to update the link.",
                null=True,
                verbose_name="Notify in",
            ),
        ),
        migrations.AddField(
            model_name="customurl",
            name="notify_interval",
            field=models.CharField(
                blank=True,
                choices=[("HOURS", "HOURS"), ("DAYS", "DAYS"), ("MONTHS", "MONTHS")],
                db_column="NotifyInterval",
                default="MONTHS",
                help_text="The interval (hours, days months) of ``notify_in``. Note that months are assumed to be 30 days.",
                max_length=6,
                null=True,
                verbose_name="Notify interval",
            ),
        ),
    ]
