# Generated by Django 3.0.5 on 2020-07-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slack_username',
            field=models.CharField(blank=True, db_column='SlackUsername', help_text="The user's slack user name registered on the CodeDevils slack channel", max_length=30, null=True, verbose_name='Slack Username'),
        ),
    ]
